[tool.poetry]
name = "nhl-reader"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
<<<<<<< HEAD
requests = "^2.32.3"
=======
>>>>>>> 75ea2b4 (complete w3e1)
rich = "^13.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
